-- LuaLS stubs for HyprLUI's Lua API (hl.plugin.hyprlui.*).
--
-- Hand-maintained, not autogenerated: Hyprland's own stub generator
-- (meta/generateLuaStubs.py in the Hyprland repo) only understands its own
-- internal hl.* binding registration pattern, and deliberately types
-- hl.plugin.<name> as `any` since it has no visibility into what a plugin
-- registers at runtime via HyprlandAPI::addLuaFunction. Keep this in sync
-- by hand with src/ui/LuaBridge.cpp/.hpp whenever the API changes.
---@meta

---@alias HyprLUI.Color integer|{r?: number, g?: number, b?: number, a?: number}
---@alias HyprLUI.Align "start"|"center"|"end"
---@alias HyprLUI.ZOrder "overlay"|"background"
---@alias HyprLUI.Anchor "top-left"|"top"|"top-right"|"left"|"center"|"right"|"bottom-left"|"bottom"|"bottom-right"
-- Same selector syntax as Hyprland's own window/layer rule `mon:` fields: a
-- direction char, "+N"/"-N", a numeric id, or a static selector/output
-- name - resolved relative to whichever monitor is focused right now,
-- ONCE, at window-creation time. No "current"/"focused" keyword on
-- purpose (it would shadow a monitor actually named "current" in the
-- user's own config) - omit `monitor` entirely for "the focused monitor",
-- and a selector that matches nothing also falls back to focused rather
-- than erroring.
---@alias HyprLUI.MonitorSelector string

-- Fields shared by every widget constructor table. `x`/`y` are honored by
-- Stack children (absolute positioning) and ignored by Row/Column children
-- (arrange() overwrites them). Numeric entries ([1], [2], ...) are child
-- widgets - see HyprLUI.WidgetSpec below.
---@class HyprLUI.WidgetCommon
---@field id? string
---@field x? number
---@field y? number
---@field visible? boolean
---@field [integer] HyprLUI.WidgetSpec

---@class HyprLUI.BoxSpec : HyprLUI.WidgetCommon
---@field w number
---@field h number
---@field color? HyprLUI.Color
---@field rounding? integer

---@class HyprLUI.TextSpec : HyprLUI.WidgetCommon
---@field text string
---@field size? integer
---@field color? HyprLUI.Color
---@field font? string

-- Manual/absolute positioning - the escape hatch. Size-to-content is the
-- bounding box of its children unless w/h are given.
---@class HyprLUI.StackSpec : HyprLUI.WidgetCommon
---@field w? number
---@field h? number

-- Flexbox-lite: packs children along the row/column axis. No wrap, no
-- justify/space-between (v1 scope - see DESIGN.md).
---@class HyprLUI.FlexSpec : HyprLUI.WidgetCommon
---@field w? number
---@field h? number
---@field gap? number
---@field padding? number
---@field align? HyprLUI.Align

---@alias HyprLUI.WidgetSpec HyprLUI.BoxSpec|HyprLUI.TextSpec|HyprLUI.StackSpec|HyprLUI.FlexSpec

-- Top-level table passed to hyprlui.window{} - the [1] entry is the root
-- widget (exactly one required: Stack/Row/Column/Text/Box).
--
-- Without `anchor`: x/y are a raw global (compositor-space) position.
-- With `anchor`: x/y are reinterpreted as an offset from that point on
-- the target monitor's usable box (positive always pushes inward).
---@class HyprLUI.WindowSpec
---@field name string
---@field x? number
---@field y? number
---@field w? number
---@field h? number
---@field zorder? HyprLUI.ZOrder
---@field anchor? HyprLUI.Anchor
---@field monitor? HyprLUI.MonitorSelector
---@field [1] HyprLUI.WidgetSpec

---@class HyprLUI.API
---@field window fun(spec: HyprLUI.WindowSpec): nil
---@field Stack fun(spec: HyprLUI.StackSpec): HyprLUI.StackSpec
---@field Row fun(spec: HyprLUI.FlexSpec): HyprLUI.FlexSpec
---@field Column fun(spec: HyprLUI.FlexSpec): HyprLUI.FlexSpec
---@field Text fun(spec: HyprLUI.TextSpec): HyprLUI.TextSpec
---@field Box fun(spec: HyprLUI.BoxSpec): HyprLUI.BoxSpec
---@field remove_canvas fun(name: string): nil
---@field set_canvas_visible fun(name: string, visible: boolean): nil
---@field set_text fun(window: string, id: string, text: string): nil
---@field remove_widget fun(window: string, id: string): nil

---@type HyprLUI.API
---@diagnostic disable-next-line: missing-fields
hl.plugin.hyprlui = {}
